### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by cyber-cliff** [talmobi/bittysound#1]
Hey bro, can you help me on who to install this? I am really noob about linux, i have shared and vps hosting. I really like your script for my project in school. Please tell me what to install on my server and the steps.

Thanks,

**Comment by cyber-cliff** [comment]
Hi,

Im getting this error with this command. " node index.js

```
module.js:328
    throw err;
    ^

Error: Cannot find module './auth.json'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\bittysound\server\src\index.js:5:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
```

**Comment by talmobi** [comment]
Hello!

I'm using a free mongolabs 500mb mongo sandbox database and I have the username and password written inside a auth.json file and then use to connect to my databse(which I .gitignore so that nobody can see my username/password and mess with it).

You can see it in lines 5 and 23-25:

```
5: var auth = require('./auth.json');
...
23: var db_url = auth.mongolab.url
24:   .replace('<dbuser>', auth.mongolab.dbuser)
25:   .replace('<dbpassword>', auth.mongolab.dbpassword);
```

The auth.json looks something like this

```
{
  "mongolab": {
    "url": "mongodb://<dbuser>:<dbpassword>@ds2092309.mongolab.com:46235/teenysong",
    "dbuser": "MY_SECRET_DB_USER",
    "dbpassword": "MY_SECRET_DB_PASSWORD"
  }
}
```

You can also see an old auth.json that I accidentally added in an earlier commit (and deleted). I had to go and change my username and passwords afterwards: https://github.com/talmobi/bittysound/commit/f90bc5fbc91860731131bf6bf51e1a2aad12758d

So you can either create your own mongo db and pass it in for mongoose.connect or make your own free 500mb sandbox in mongolabs.com and use that.

Hope this helps.

**Comment by cyber-cliff** [comment]
WOW! thanks, it works now.

**Comment by talmobi** [comment]
Coolbeans (:

**Comment by cyber-cliff** [comment]
Last question bro, how run this with my domain? im currently running it now on my windows local? How to run this on my host thanks,

**Comment by talmobi** [comment]
Login to your vps through ssh. Clone and install the project just like you did locally. Run the server. Done.

To point your DNS to your server (ip address) is a different matter. And setting up sub domains or paths to point to the bittysound server/service (which runs by default on port 50005) is usually done by running nginx or apache on port 80 and configuring them to pass on the request (based on sub domain names or paths or just by default) to your service running on port 50005.

Alternatively you can run the bittysound server directly on port 80 - which is the default port that web browsers use (specified in the HTTP protocol) when you type in an address (which is why you don't see it in the address bar unless you type it in yourself ex: www.google.com:80).

**Comment by cyber-cliff** [comment]
Thanks got it right now. but i have a problem on download. when i click the download button no songs are donwloaded. check this log.

progress listener added to: 154646251
track id: 154646251
queue advanced
length: 58328710
filesize: 55.6265926361084 MB
Successfully downloaded track
sendng binary data file to user
track id: 154646251
queue advanced
length: 58328710
C:\mp3hq\server\src\progress_server.js:25
  var lastTime = sockets.lastTime;
                        ^

TypeError: Cannot read property 'lastTime' of null
    at Object.update (C:\mp3hq\server\src\progress_server.js:25:25)
    at Request.<anonymous> (C:\mp3hq\server\src\api.js:132:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (C:\mp3hq\server\src\node_modules\request\req
uest.js:960:12)
    at emitOne (events.js:90:13)
    at IncomingMessage.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:147:16)
    at IncomingMessage.Readable.push (_stream_readable.js:111:10)
    at HTTPParser.parserOnBody (_http_common.js:110:22)
    at TLSSocket.socketOnData (_http_client.js:315:20)
    at emitOne (events.js:90:13)
    at TLSSocket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:147:16)
    at TLSSocket.Readable.push (_stream_readable.js:111:10)
    at TLSWrap.onread (net.js:525:20)
